In [1]:
print('Hi!!')

Hi!!


In [2]:
import numpy

In [3]:
a=['hi',2,'a',24]

In [4]:
a[1:]

[2, 'a', 24]

In [2]:
'Yo'

'Yo'

In [9]:
ls1 = [0,1,2,3,4,5,6]

In [11]:
ls1[-1:0:-1]

[6, 5, 4, 3, 2, 1]

In [21]:
#loop is in the same scope in python
for i in range (0,10):
    j=i+1
    print(i)

0
1
2
3
4
5
6
7
8
9


In [22]:
print(j)

10


In [27]:
k=0
while(k<5):
    m=2
    print(k)
    k=k+1;
    
print('m is {}'.format(m))

0
1
2
3
4
m is 2


In [29]:
import numpy as np

In [31]:
arr=[0,1,2,3,4,5,6,7,8,9]

In [34]:
A=np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
from math import *
num1=int(sqrt(100))
num2=round(sin(3.141/2))
num1,num2

(10, 1)

In [58]:
A2=np.arange(0,50,2).reshape(5,5)
A2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [60]:
A2[0::2,0::3]

array([[ 0,  6],
       [20, 26],
       [40, 46]])

In [66]:
A2[0]=[100,50,25,12,6]
A2

array([[100,  50,  25,  12,   6],
       [ 10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28],
       [ 30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48]])